spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: admin
    password: 123
  jpa:
    generate-ddl: false
    show-sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
