spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/maindb
    username: joao
    password: 123
  jpa:
    generate-ddl: false
    show-sql: true
