management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: Market ERP
    description: ERP para mercados
    author: joaopmaximo
    version: '@project.version@'

spring:
  profiles:
    active: dev-h2

jwt:
  public.key: classpath:app.key.pub
  private.key: classpath:app.key

app:
  imgDir: ${user.dir}/imgs