management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: Mixzyn ERP
    description: ERP para mercados
    author: joaopmaximo
    version: '@project.version@'
spring:
  profiles:
    active: dev-h2