spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maindb
    username: admin
    password: admin
  jpa:
    generate-ddl: false
    show-sql: true
